### ISSUE TITLE
Basic User module

### ISSUE THREAD

**Issue by srmanikandasriram** [The-WebOps-Club/project-management-portal#1]
Implement basic Registration flow.
Include the following:
1. Edit profile
2. Change password
3. Forgot password
4. E-mail activation
5. Profile page

**Comment by raghu1kalluri** [comment]
Account editing part done except for image upload. The frontend part consists of positioning the li elements.
Will use django-registration package for account creation.

**Comment by srmanikandasriram** [comment]
Basic parts in place. closing this. Will open separate issues for finer details
